version: '3.1'

services:
  docker-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=restaurant
      - MYSQL_PASSWORD=12345

  spring-boot-jpa-docker-webapp:
    environment:
      - spring.datasource.username=root
      - spring.datasource.password=12345
      - spring.jpa.hibernate.dll-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://docker-mysql:3306/restaurant?createDatabaseIfNotExist=true
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    restart: on-failure